import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const products = [
  // GORRAS
  {
    name: 'Gorras Ojo de Angel',
    category: 'gorras',
    price: 420,
    description: 'Gorras Ojo de Angel Dry Fit - Blanca (Baseball)',
    colors: ['Cyan', 'Marrón', 'Blanco', 'Rojo', 'Verde', 'Azul', 'Negro'],
    imageUrl: '/imagenes/Gorras Ojo de Angel.svg',
    tags: ['best-seller'],
    sortOrder: 1,
  },
  {
    name: 'Gorras de Mallas Sublimables',
    category: 'gorras',
    price: 400,
    description: 'Gorras de Mallas Sublimables - Blanca (Trucker)',
    colors: ['Cyan', 'Marrón', 'Blanco', 'Rojo', 'Verde', 'Azul', 'Negro'],
    imageUrl: '/imagenes/Gorras de Mallas Sublimables.svg',
    tags: [],
    sortOrder: 2,
  },
  {
    name: 'Gorras de Mallas Blanca y Negra',
    category: 'gorras',
    price: 400,
    description: 'Gorras de Mallas Sublimables - Blanca y Negra (Trucker)',
    colors: ['Cyan', 'Marrón', 'Blanco', 'Rojo', 'Verde', 'Azul', 'Negro'],
    imageUrl: '/imagenes/Gorras de Mallas Sublimables (2).svg',
    tags: ['best-seller'],
    sortOrder: 3,
  },
  // TSHIRTS
  {
    name: 'Tshirt Ojo de Angel',
    category: 'tshirts',
    price: 550,
    description: 'Tshirt, tipo de tela: Ojo de ángel. Diferentes tipos de telas',
    colors: ['Cyan', 'Marrón', 'Blanco', 'Rojo', 'Verde', 'Azul', 'Negro'],
    imageUrl: '/imagenes/TSHIRT _ TELA OJO DE ANGEL.svg',
    note: 'A PARTIR DE 2 BAJA EL PRECIO',
    tags: ['best-seller'],
    sortOrder: 10,
  },
  {
    name: 'Tshirt Poliester',
    category: 'tshirts',
    price: 550,
    description: 'Tshirt, tipo de tela: Poliester. Diferentes tipos de telas',
    colors: ['Cyan', 'Marrón', 'Blanco', 'Rojo', 'Verde', 'Azul', 'Negro'],
    imageUrl: '/imagenes/TSHIRT _ TELA POLIESTER.svg',
    note: 'A PARTIR DE 2 BAJA EL PRECIO',
    tags: [],
    sortOrder: 11,
  },
  {
    name: 'Hoodie Poliester',
    category: 'tshirts',
    price: 1400,
    description: 'Hoodie, tipo de tela: Poliester. Diferentes tipos de telas',
    colors: ['Cyan', 'Marrón', 'Blanco', 'Rojo', 'Verde', 'Azul', 'Negro'],
    imageUrl: '/imagenes/HOODIE _ TELA POLIESTER.svg',
    note: 'A PARTIR DE 2 BAJA EL PRECIO',
    tags: [],
    sortOrder: 12,
  },
  {
    name: 'Tshirt Algodón',
    category: 'tshirts',
    price: 500,
    description: 'Tshirt, tipo de tela: Algodón',
    colors: ['Cyan', 'Marrón', 'Blanco', 'Rojo', 'Verde', 'Azul', 'Negro'],
    imageUrl: '/imagenes/TSHIRT _ TELA OJO DE ANGEL.svg',
    note: 'VARÍA DEPENDIENDO TAMAÑO Y CANTIDAD',
    tags: [],
    sortOrder: 13,
  },
  // TAZAS
  {
    name: 'Tazas Blancas Sublimables',
    category: 'tazas',
    price: 400,
    description: 'Tazas Blancas Sublimables 11oz con Cajas',
    colors: ['Cyan', 'Marrón', 'Blanco', 'Rojo', 'Verde', 'Azul', 'Negro'],
    imageUrl: '/imagenes/TAZAS BLANCAS.svg',
    tags: ['best-seller'],
    sortOrder: 20,
  },
  {
    name: 'Taza Degradado 11oz',
    category: 'tazas',
    price: 450,
    description: 'Taza Frosted Degradado 11Onz. Sublimable (C-36)',
    colors: ['Cyan', 'Marrón', 'Blanco', 'Rojo', 'Verde', 'Azul', 'Negro'],
    imageUrl: '/imagenes/TAZA DEGRADADO 11ONZ.svg',
    tags: ['trending'],
    sortOrder: 21,
  },
  {
    name: 'Tazas Cambio de Color',
    category: 'tazas',
    price: 450,
    description: 'Negra Semi-Glossy 11 Onzas (C-48)',
    colors: ['Cyan', 'Marrón', 'Blanco', 'Rojo', 'Verde', 'Azul', 'Negro'],
    imageUrl: '/imagenes/TAZAS CAMBIO DE COLOR.svg',
    tags: [],
    sortOrder: 22,
  },
  // TERMOS
  {
    name: 'Termo Aluminio 600ML',
    category: 'termos',
    price: 550,
    description: 'Termo / Botella de Agua, Sublimación Aluminio 600ML (White) (CJA 60)',
    colors: ['Blanco', 'Negro'],
    imageUrl: '/imagenes/TERMO _ BOTELLA DE AGUA.svg',
    tags: [],
    sortOrder: 30,
  },
  {
    name: 'Vaso Blanco de Acero',
    category: 'termos',
    price: 1200,
    description: 'Vaso Blanco de Acero Inoxidable para Sublimación 20ONZ (C-25)',
    colors: ['Blanco', 'Negro'],
    imageUrl: '/imagenes/VASO BLANCO DE ACERO.svg',
    tags: ['best-seller'],
    sortOrder: 31,
  },
  {
    name: 'Termos Acero Inoxidable',
    category: 'termos',
    price: 1050,
    description: 'Termos Acero Inoxidable Blanca 14 Onzas (C-48)',
    colors: ['Blanco', 'Negro'],
    imageUrl: '/imagenes/TERMOS ACERO INOXIDABLE.svg',
    tags: [],
    sortOrder: 32,
  },
  {
    name: 'Lata de Cola White',
    category: 'termos',
    price: 950,
    description: 'Lata de Cola White en Acero Inoxidable Sublimación 17 ONZ (C-60)',
    colors: ['Blanco', 'Negro'],
    imageUrl: '/imagenes/LATA DE COLA WHITE.svg',
    tags: [],
    sortOrder: 33,
  },
  {
    name: 'Botella de Agua 17oz',
    category: 'termos',
    price: 1100,
    description: 'Botella de Agua para Sublimación Blanca 17ONZ 500ML Acero Inoxidable',
    colors: ['Blanco', 'Negro'],
    imageUrl: '/imagenes/BOTELLA DE AGUA.svg',
    tags: [],
    sortOrder: 34,
  },
  {
    name: 'Botella de Agua Aluminio',
    category: 'termos',
    price: 750,
    description: 'Botella de Agua, Aluminio White 650ML (CJA 60)',
    colors: ['Blanco', 'Negro'],
    imageUrl: '/imagenes/TERMO _ BOTELLA DE AGUA (2).svg',
    tags: [],
    sortOrder: 35,
  },
  {
    name: 'Vasos Luminosos',
    category: 'termos',
    price: 1200,
    description: 'Vasos luminosos (Blanco a Verde) 20oz/600ml Tapa y Sorbete - Acero Inoxidable (C-25)',
    colors: ['Blanco', 'Negro'],
    imageUrl: '/imagenes/VASOS LUMINOSOS.svg',
    tags: ['trending'],
    sortOrder: 36,
  },
  // LLAVEROS
  {
    name: 'Llavero de Piel',
    category: 'llaveros',
    price: 400,
    description: 'Llavero de Piel - Cuadrado - Sublimación',
    colors: ['Blanco', 'Negro'],
    imageUrl: '/imagenes/LLAVERO DE PIEL.svg',
    tags: [],
    sortOrder: 40,
  },
  {
    name: 'Llavero de Metal Rectangular L',
    category: 'llaveros',
    price: 400,
    description: 'Llavero de Metal - Rectangular L - Sublimación',
    colors: ['Blanco', 'Negro'],
    imageUrl: '/imagenes/LLAVERO DE METAL.svg',
    tags: [],
    sortOrder: 41,
  },
  {
    name: 'Llavero de Metal Esquina Redondas',
    category: 'llaveros',
    price: 400,
    description: 'Llavero de Metal - Rectangular Esquina Redondas - Sublimación',
    colors: ['Blanco', 'Negro'],
    imageUrl: '/imagenes/LLAVEROS DE METAL.svg',
    tags: [],
    sortOrder: 42,
  },
  {
    name: 'Llavero de Metal Octagonal',
    category: 'llaveros',
    price: 190,
    description: 'Llavero de Metal - Octagonal - Sublimación',
    colors: ['Blanco', 'Negro'],
    imageUrl: '/imagenes/LLAVERO DE METAL (2).svg',
    tags: [],
    sortOrder: 43,
  },
  // OTROS
  {
    name: 'Mouse Pad',
    category: 'otros',
    price: 550,
    description: 'Mouse pad - Cuadrado - Sublimación',
    colors: ['Blanco', 'Negro'],
    imageUrl: '/imagenes/MOUSE PAD.svg',
    tags: ['best-seller'],
    sortOrder: 50,
  },
  {
    name: 'Cover Personalizado',
    category: 'otros',
    price: 600,
    description: 'Cover - Varios modelos - Sublimación',
    colors: ['Blanco', 'Negro'],
    imageUrl: '/imagenes/COVER PERSONALIZADO.svg',
    tags: [],
    sortOrder: 51,
  },
];

async function main() {
  console.log('Sembrando productos del website...');
  for (const p of products) {
    await prisma.websiteProduct.upsert({
      where: { id: p.name.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '') },
      update: {},
      create: {
        id: p.name.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, ''),
        ...p,
        isActive: true,
      },
    });
    console.log(`  ✓ ${p.name}`);
  }
  console.log(`Listo: ${products.length} productos sembrados.`);
}

main()
  .catch(e => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
